name: Install and Archive

on:
  push:
    branches: [ "openimageio-2.3.7-py39", "github-actions" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Bootstrap vcpkg
      run: .\bootstrap-vcpkg.bat

    - name: Install OpenImageIO
      run: .\vcpkg install openimageio[pybind11,tools]:x64-windows

    - name: Create a tarball
      run: |
        powershell Compress-Archive -Path packages\openimageio -DestinationPath oiio-2.3.7-py39-win32.zip

    # - name: Release the tarball
    #   uses: ncipollo/release-action@v1.14.0
    #   with:
    #     artifacts: "oiio-2.3.7-py39-win32.zip"
    #     tag: 2.3.7
